# Set Application Name
spring:
  application:
    name: zuul-api-gateway
    
# Set Server port
server:
  port: ${PORT:8080}
  
# Information about Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  routes:
    product-service:
      path: /product-service/**
      url: http://localhost:9001      