# Set Application Name
spring:
  application:
    name: product-service
    
# Set Server port
server:
  port: ${PORT:9001}
  
# Information about Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/